[WIP]
Minhacps/votacidade-app pull request #146
Opened 2020-10-23 05:30 UTC by notnotgabriel

Resolve #143 

Done
- Adiciona rota para perfil publico;
- CTA para cadastro no topo levando para a home;
- Share do whats;
- Copiar link atual para o clipboard (ctrl c/v);

WIP
- Botão de share do facebook;
- Adicionar informações de cadastro das pessoas candidatas na bio;
- Revisar/tratar texto de share no geral (Está num contexto de pessoa candidata);
- Testes

### Demonstracao
![vota](https://user-images.githubusercontent.com/5247142/96960006-a4c79700-14d7-11eb-9160-23a958c0e32c.gif)

## Verificações

Assinale as verificações abaixo:

* [ x ] Eu li e segui o [Guia de Contribuição](https://github.com/Minhacps/votacidade/blob/master/.github/CONTRIBUTING.md).
* [ x ] Eu li e segui o [Código de Conduta](https://github.com/Minhacps/votacidade/blob/master/.github/CODE_OF_CONDUCT.md).
* [ x ] Eu confirmei que não há outra [Pull Request](https://github.com/Minhacps/votacidade/pulls) para a mesma alteração.

2020-10-23 11:18 UTC, lguima commented
@notnotgabriel pra manter a PR como em progresso, vc pode colocar ela como Draft

2020-10-23 12:20 UTC, luistak requested changes
Seria legal adicionar alguns testes pra garantir estes novos fluxos, seja a navegação para essas rotas, quanto as ações em sí

2020-10-23 12:20 UTC, luistak commented on src/App.js
> +      <Switch>
Sugiro checar uma rota que não está mapeada aqui

2020-10-23 12:20 UTC, luistak commented on src/components/ShareButtons/ShareButtons.js
> +  const whatsAppText = `Acabei de utilizar o Vota Cidade em ${cityName} e compartilho com vocês o que respondi ${currentUrl}`;
Os textos poderiam vir de um CMS no futuro, onde ficaria mais fácil revisar/corrigir sem um novo deploy ❤️

2020-10-23 12:20 UTC, luistak commented on src/components/ShareButtons/ShareButtons.js
> +      timer = setTimeout(() => {
é pra ser um setTimeout ou setInterval?

2020-10-23 12:20 UTC, luistak commented on src/pages/Profile/Profile.styled.js
> +  // border-bottom: 1px solid ${colors.grey300};
```suggestion
```

2020-10-23 16:58 UTC, notnotgabriel commented on src/components/ShareButtons/ShareButtons.js
> +  const whatsAppText = `Acabei de utilizar o Vota Cidade em ${cityName} e compartilho com vocês o que respondi ${currentUrl}`;
Gosto!

2020-10-23 16:58 UTC, notnotgabriel commented on src/components/ShareButtons/ShareButtons.js
> +      timer = setTimeout(() => {
Timeout mesmo. A ideia é fazer um tooltip de feedback que copiou o link, que depois de 3s some.
Na hora de refatorar eu vou mudar o botão e logica pra um componente especifico.

2020-10-23 16:59 UTC, notnotgabriel commented on src/pages/Profile/Profile.styled.js
> +  // border-bottom: 1px solid ${colors.grey300};
Calma que eu ainda vou voltar isso eu acho :P

2020-10-23 17:00 UTC, notnotgabriel commented on src/App.js
> +      <Switch>
> @notnotgabriel pra manter a PR como em progresso, vc pode colocar ela como Draft

Tks Guima! É costume porque faço assim no trabalho.
Acho que depois do PR aberto não da pra mudar mais pra draft né?

2020-10-23 17:01 UTC, notnotgabriel commented
> @notnotgabriel pra manter a PR como em progresso, vc pode colocar ela como Draft

Tks Guima! É costume porque faço assim no trabalho.
Acho que depois do PR aberto não da pra mudar mais pra draft né?

2020-10-23 17:01 UTC, notnotgabriel commented on src/App.js
> +      <Switch>
Qual rota? Acho que não entendi mano.

2020-10-23 17:02 UTC, notnotgabriel commented
> Seria legal adicionar alguns testes pra garantir estes novos fluxos, seja a navegação para essas rotas, quanto as ações em sí

Show com ctz!

2020-10-26 11:36 UTC, luistak commented on src/App.js
> +      <Switch>
Tipo acessar um `/kleber-shasjadhsd` e ver onde que ele vai redirecionar

2020-11-03 01:57 UTC, luistak approved these changes

2020-11-03 01:57 UTC, luistak commented on src/components/ShareButtons/ClipboardButton.js
> +import colors from 'styles/colors';
Nos poderíamos começar a usar os Temas do styled-components no futuro, o que acha?

2020-11-03 01:57 UTC, luistak commented on src/components/ShareButtons/ClipboardButton.js
> +        defaultValue={`${text}`}
O texto já não é uma string?

2020-11-03 01:57 UTC, luistak commented on src/tests/mockFirebaseAuth.js
> +export const mockProfileDatabase = (candidate, candidateAnswers) => {
Nice!

2020-11-03 02:00 UTC, notnotgabriel commented on src/components/ShareButtons/ClipboardButton.js
> +import colors from 'styles/colors';
eu acho um q seria um refactor showw emm

2020-11-03 02:00 UTC, notnotgabriel commented on src/components/ShareButtons/ClipboardButton.js
> +        defaultValue={`${text}`}
🤔 💭💭💭💭

2020-11-03 02:01 UTC, notnotgabriel commented on src/tests/mockFirebaseAuth.js
> +export const mockProfileDatabase = (candidate, candidateAnswers) => {
Inclusive não funfou asserção sobre o mock acho que ficou faltando isso no teste

2020-11-03 11:05 UTC, jooaodias approved these changes

2020-11-03 20:41 UTC, merged