Sincroniza firestore a cada 5 respostas
Minhacps/votacidade-app pull request #156
Opened 2020-11-04 11:06 UTC by victormiguez

## Verificações

Assinale as verificações abaixo:

* [x] Eu li e segui o [Guia de Contribuição](https://github.com/Minhacps/votacidade/blob/master/.github/CONTRIBUTING.md).
* [x] Eu li e segui o [Código de Conduta](https://github.com/Minhacps/votacidade/blob/master/.github/CODE_OF_CONDUCT.md).
* [x] Eu confirmei que não há outra [Pull Request](https://github.com/Minhacps/votacidade/pulls) para a mesma alteração.

## O que foi alterado

Anteriormente estávamos chamando o firestore no componente Question, agora usamos a função `updateAnswers` do `AnswersProvider` para fazer isso.
No provider temos um acumulador que é incrementado depois de cada resposta e sincroniza os dados com o firestore a cada 5 respostas ou caso seja a última resposta.

O objetivo desse PR é otimizar número de escritas que fazemso no firestore, não importa o tamanho do objeto que estamos escrevendo e sim quantas vezes. Por isso agora sempre sincronizamos todas as respostas e o firestore cuida de fazer o diff e sobrescrever apenas o necessário.
Optei por não usar o localstorage nessa primeira implementação para fazer o mais simples possível e incrementar o que for necessário depois.

2020-11-04 13:04 UTC, luistak requested changes
Belo trabalho!

2020-11-04 13:04 UTC, luistak commented on src/components/AnswersProvider/AnswersProvider.test.js
> +  it('synchronize the list of answers in batch', async () => {
Eu não fiquei feliz com o nome desse teste, só lendo o nome dele não ficou claro que deveria garantir a sincronização a cada 5 respostas

2020-11-04 13:04 UTC, luistak commented on src/components/AnswersProvider/AnswersProvider.test.js
> +    });
Você poderia iterar em um for vazio e disparar tudo e depois fazer a asserção +- assim:

```js
    expect(questionsService.syncAnswers).toBeCalledTimes(2);
``
`

2020-11-04 13:04 UTC, luistak commented on src/components/AnswersProvider/AnswersProvider.test.js
> +  it('synchronize answers when it is the last one', async () => {
```suggestion
  it('should synchronize answers when it is the last one', async () => {
```

2020-11-05 23:46 UTC, victormiguez commented
@luistak pode revisar de novo?

2020-11-06 22:08 UTC, luistak commented on src/components/AnswersProvider/AnswersProvider.test.js
> +    });
Nice approach!

2020-11-06 22:11 UTC, luistak approved these changes

2020-11-06 22:11 UTC, luistak commented on src/components/AnswersProvider/AnswersProvider.test.js
> +        fireEvent.click(addAnswerButton);
[Small improvement](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#not-using-testing-libraryuser-event), but this is not needed in this pr

2020-11-06 22:11 UTC, luistak commented on src/components/AnswersProvider/AnswersProvider.test.js
> +        fireEvent.click(addAnswerButton);
You could replace every usage also in this file but this is not needed.

2020-11-07 00:01 UTC, merged