Compartilhamento do Vota
Minhacps/votacidade-app pull request #160
Opened 2020-11-09 00:42 UTC by jooaodias

## Verificações

Assinale as verificações abaixo:

* [X] Eu li e segui o [Guia de Contribuição](https://github.com/Minhacps/votacidade/blob/master/.github/CONTRIBUTING.md).
* [X] Eu li e segui o [Código de Conduta](https://github.com/Minhacps/votacidade/blob/master/.github/CODE_OF_CONDUCT.md).
* [X] Eu confirmei que não há outra [Pull Request](https://github.com/Minhacps/votacidade/pulls) para a mesma alteração.

2020-11-10 12:22 UTC, luistak requested changes
Booa belo PR!

Mas eu recomendo adicionar alguns testes para garantir estes novos comportamentos

2020-11-10 12:22 UTC, luistak commented on src/pages/ShareImage/ShareImage.js
> +          {cityName === 'Americna' && (
Typo

2020-11-10 12:22 UTC, luistak commented on src/pages/ShareImage/ShareImage.js
> +const ShareImage = () => {
Este componente acaba não escalando e fica difícil de dar manutenção oq eu recomendo é fazer algum mapa de cidades e utilizar ele no `ShareImage`, assim como nesse exemplo abaixo meramente ilustrativo

```jsx
const citySharing = { // Isso aqui evita mto retrabalho e ctrl c ctrl v
  'Campinas': {
    img: divulgaCmp,
    download: 'Vota-Campinas.png',
  },
  'João Pessoa': {
    img: divulgaJampa,
    download: 'Vota-Jampa.png',
  }
  ...
}

const ShareImage = () => {
  const { cityName } = useContext(CityContext);

  const sharingData = citySharing[cityName];
  if (!sharingData) { // Always try to use early return
    return null;
  }

  return (
    <Container className="py-4">
      <Row className="justify-content-center">
        <Col md="6">
          <img
            src={sharingData.img}
            alt={'Imagem de compartilhamento do Vota'}
            className="rounded w-100"
          />
          <CenteredContent>
            <a href={sharingData.img} download={sharingData.download}>
              <StyledButton>Compartilhe o Vota!!</StyledButton>
            </a>
          </CenteredContent>
        </Col>
      </Row>
    </Container>
  );
};

```

2020-11-11 12:58 UTC, jooaodias commented on src/pages/ShareImage/ShareImage.js
> +          {cityName === 'Americna' && (
Opss

2020-11-11 13:13 UTC, jooaodias commented on src/pages/ShareImage/ShareImage.js
> +const ShareImage = () => {
Obrigado pela ajuda @luistak !! Eu nem tinha pensando em fazer desta maneira e agora eu aprendi😅
Já fiz as alterações aqui.

2020-11-21 17:11 UTC, luistak approved these changes

2020-11-24 20:11 UTC, merged